retargeting:
  type: DexPilot

  # Overridden by the ROS launch file. It stays here because RetargetingConfig
  # requires the field to exist before applying overrides.
  urdf_path: /workspace/models/dg5f/urdf/dg5f_right.urdf

  target_joint_names:
    - rj_dg_1_1
    - rj_dg_1_2
    - rj_dg_1_3
    - rj_dg_1_4
    - rj_dg_2_1
    - rj_dg_2_2
    - rj_dg_2_3
    - rj_dg_2_4
    - rj_dg_3_1
    - rj_dg_3_2
    - rj_dg_3_3
    - rj_dg_3_4
    - rj_dg_4_1
    - rj_dg_4_2
    - rj_dg_4_3
    - rj_dg_4_4
    - rj_dg_5_1
    - rj_dg_5_2
    - rj_dg_5_3
    - rj_dg_5_4

  wrist_link_name: rl_dg_palm
  finger_tip_link_names:
    - rl_dg_1_tip
    - rl_dg_2_tip
    - rl_dg_3_tip
    - rl_dg_4_tip
    - rl_dg_5_tip

  scaling_factor: 1.0


  low_pass_alpha: 0.2
  has_joint_limits: true
